stages:
  - build

default:
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

build-db:
  stage: build
  image: docker
  services: 
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/db -f FPLV2.Database/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/db

build-updater:
  stage: build
  image: docker
  services: 
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/updater -f FPLV2.Updater/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/updater